# Configuration file: variable parameters
# =======================================
input_file: "text" #or 'audio'

PATH_TO_PROJECT_FOLDER: "/home/yvespauli/PycharmProjects/KetamineStudy/KetamineStudy_ProjectFolder/" # Set default to home directory, e.g., '/home/usr/...'
language: "german" # Possibly add options for German and English
numberOfSubjects: null # Specify number of subjects; if 'None', number of subjects is automatically detected
multipleSessions: false # Set to True if multiple sessions per subject

task_names:
  - "sampleTask" # Give names of tasks used for creation of the text file (e.g., ['fluency', 'interview'])
corpus_names:
  - "Ketamin"
  - "Placebo" # Names of individual categories to group together

tokenization: "wordLevel" # Options: 'characterLevel', 'subWordLevel'

# Options for extract_logits
chunk_size: null
overlap_size: null

cleaning_options:
  general_cleaning: true # General cleaning options used for most text preprocessing, default: True.
  remove_punctuation: true
  lowercase: true
  remove_brackets_and_bracketcontent: true

general_cleaning_options:
  strip_whitespace: true
  merge_multiple_whitespaces: true
  remove_whitespace_before_punctuation: true
  merge_newline_characters: true
  remove_backslashes: true

tokenization_options:
  method: "model_instance" # Options: model_instance, regex, nltk, etc.
  model_name: "DiscoResearch/Llama3-German-8B-32k" # Replace with your model instance name

normalization_options:
  method: "lemmatization" # Options: lemmatization or stemming
