from setuptools import setup, find_namespace_packages

setup(
    name='pelican-nlp',
    version='0.1.1',
    description='Preprocessing and Extraction of Linguistic Information for Computational Analysis',
    long_description=open('README.rst').read(),
    long_description_content_type='text/x-rst',
    url='https://github.com/ypauli/PELICAN-nlp',
    author='Yves Pauli',
    author_email='yves.pauli@gmail.com',
    license='Attribution-NonCommercial 4.0 International',
    packages=find_namespace_packages(include=['pelican_nlp*']),
    package_data={
        'pelican_nlp': [
            'configuration_files/*.yml',
            'sample_configuration_files/*.yml',
        ],
    },
    install_requires=[
        'numpy>=1.23.0,<2.0.0',
        'pandas>=1.5.0,<2.0.0',
        'pyyaml>=6.0.2',
        'torch>=2.5.1',
        'spacy>=3.7.2,<3.9.0',
        'transformers>=4.37.2,<4.42.0',
        'docx2txt>=0.8',
        'striprtf>=0.0.28',
        'chardet>=4.0.0',
        'scikit_learn>=1.6.1',
        'scipy>=1.15.2',
        'fasttext>=0.9.3',
        'matplotlib>=3.10.1',
        'seaborn>=0.13.2',
        'accelerate>=1.1.1',
        'editdistance>=0.8.1',
        'psutil>=6.1.0',
        'tqdm>=4.66.5',
        'pytest>=8.3.4',
        'statsmodels>=0.14.4'
    ],
    extras_require={
        'normalization': [
            'spacy>=3.7.2,<3.9.0',
        ],
    },
    python_requires='>=3.6',
    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Scientific/Engineering :: Artificial Intelligence',
        'Topic :: Text Processing :: Linguistic',
    ],
    project_urls={
        'Bug Reports': 'https://github.com/ypauli/PELICAN-nlp/issues',
        'Source': 'https://github.com/ypauli/PELICAN-nlp',
        'Documentation': 'https://github.com/ypauli/PELICAN-nlp#readme',
    },
)
