# Transcription Configuration File
# ================================

# Basic Settings
# -------------
input_file: "audio"  # Set to 'audio' for transcription
language: "german"

# Task Configuration
# -----------------
task_name: "interview"  # Name of task used for creation of data
fluency_task: &fluency_flag false
discourse: &discourse_flag true  # Enable discourse for speaker diarization

# Corpus Configuration
# ------------------
corpus_key: "group" # Entity key to group files for analysis
corpus_values:  # Corresponding entity values found in dataset
  - "control"
  - "treatment"

# Session and participant Settings
# --------------------------
multiple_sessions: false
number_of_participants: null  # If null, auto-detected
number_of_speakers: 2 # Specify amount of speakers for discourse files
participant_speakertag: "B"  # Speaker tag for participant

# Document Structure
# ----------------
has_multiple_sections: false
has_section_titles: false
section_identification: null
number_of_sections: null

# Processing Pipeline
# -----------------
pipeline_options:
  quality_check: false
  clean_text: true
  tokenize_text: false
  normalize_text: false

# Transcription Configuration
# -------------------------
transcription:
  hf_token: "your_hugging_face_token_here"  # Required for speaker diarization
  num_speakers: 2  # Expected number of speakers (falls back to number_of_speakers if not set)
  min_silence_len: 1000  # Minimum silence length for splitting (ms)
  silence_thresh: -30  # Silence threshold in dBFS
  min_length: 90000  # Minimum chunk length (ms)
  max_length: 150000  # Maximum chunk length (ms)
  timestamp_source: "whisper_alignments"  # Options: 'whisper_alignments' or 'forced_alignments'
  diarizer_params:  # Optional: Custom diarization parameters
    segmentation:
      min_duration_off: 0.0
    clustering:
      method: "centroid"
      min_cluster_size: 12
      threshold: 0.8

# Metric Extraction
# ---------------
metrics_to_extract: ["embeddings"]  # Options: 'embeddings', 'logits'
output_document_information: true

# Cleaning Options
# --------------
cleaning_options:
  general_cleaning: true
  remove_punctuation: false
  lowercase: true
  remove_brackets_and_bracketcontent: false
  remove_timestamps: false
  timestamp_pattern_example: null
  fluency_task: *fluency_flag
  word_splitter: ';'
  remove_hyphens: true
  remove_duplicates: true

general_cleaning_options:
  strip_whitespace: true
  merge_multiple_whitespaces: true
  remove_whitespace_before_punctuation: true
  merge_newline_characters: true
  remove_backslashes: true

# Embedding Options
# ---------------
options_embeddings:
  tokenization_method: "whitespace"
  model_name: "fastText"
  pytorch_based_model: false
  method: "model_instance"
  max_length: 512
  clean_embedding_tokens: true
  remove_punctuation: false
  lowercase: false
  keep_speakertags: true  # Keep speaker tags for discourse analysis
  semantic-similarity: true
  window_size: null
  divergence_from_optimality: false
  output_options:
    exclude_special_tokens: true
    remove_'_'_character: true
    remove_speaker_labels: false  # Keep speaker labels for discourse
    remove_punctuation_and_symbols: true
    remove_brackets_and_content: true

# Logits Options
# -------------
options_logits:
  chunk_size: 128
  overlap_size: 64
  tokenization_method: "model"
  model_name: "DiscoResearch/Llama3-German-8B-32k"
  remove_punctuation: true
  lowercase: true
  keep_speakertags: true

# Analysis Options
# --------------
options_semantic-similarity:
  window_sizes:
    - 2
    - 8

options_dis_from_randomness:
  window_size: 8
  min_len: null
  bootstrap: 10000
  shuffle_mode: 'include0_includeN'
  parallel_computing: false

# Normalization Options
# -------------------
normalization_options:
  method: "lemmatization"

# Document Information Output
# -------------------------
document_information_output:
  parameters:
    - participant_ID
    - recording_length
    - transcription_file

# Filename Configuration
# --------------------
filename_components:
  participant: true
  session: false
  task: true
  task_addition: false
  corpus: true
  metric: true
  additional_tags: []

# Additional Settings
# -----------------
create_aggregation_of_results: true
