# Configuration file: variable parameters
# =======================================
input_file: "text" #or 'audio'

PATH_TO_PROJECT_FOLDER: "/home/yvespauli/PycharmProjects/FluencyTest" # Set default to home directory, e.g., '/home/usr/...'
language: "german" # Possibly add options for German and English
number_of_subjects: null # Specify number of subjects; if 'null', number of subjects is automatically detected
multiple_sessions: false # Set to True if multiple sessions per subject

recompute_everything: true #If set to 'false' pelican will try to reuse previously computed results stored on your drive

has_multiple_sections: false #evaluated independently
has_section_titles: false
section_identification: null #e.g. "Section:", 'null' if file does not have multiple sections, use pattern that is unlikely to appear in rest of transcript
number_of_sections: 1 #if 'null' number of sections automatically detected, however, specifying number recommended if known.

discourse: false
number_of_speakers: 1
subject_speakertag: null

task_name: "fluency" # Give name of task used for creation of the input file (e.g., ['fluency', 'interview'])
fluency_task: &fluency_flag true
corpus_names:
  - "animals"

metric_to_extract: "embeddings"
extract_logits: null
extract_embeddings: true

pipeline_options:
  quality_check: false
  clean_text: true
  tokenize_text: false
  normalize_text: false

tokenization: "wordLevel" # Options: 'characterLevel', 'subWordLevel'

# Options for extract_logits
chunk_size: null
overlap_size: null

# Options for extract_embeddings
window_sizes: [2]
metric_function: cosine_similarity
aggregation_functions: mean_of_means

cleaning_options:
  general_cleaning: false # General cleaning options used for most text preprocessing, default: True.
  remove_punctuation: false
  lowercase: true
  remove_brackets_and_bracketcontent: false
  remove_timestamps: false
  timestamp_pattern_example: null #e.g. "#00:00:23-00#"
  #Options for fluency tasks
  fluency_task: *fluency_flag
  word_splitter: ';'
  remove_hyphens: true
  remove_duplicates: true

general_cleaning_options:
  strip_whitespace: true
  merge_multiple_whitespaces: true
  remove_whitespace_before_punctuation: true
  merge_newline_characters: true
  remove_backslashes: true

tokenization_options_logits:
  method: "model_instance" # Options: model_instance, regex, nltk, etc.
  model_name: "DiscoResearch/Llama3-German-8B-32k" # Replace with your model instance name

options_embeddings:
  tokenization_method: "whitespace" #or "model"
  max_length: 512 #max sequence length
  model_name: "fastText" #e.g. "fastText", "xlm-roberta-base"
  pytorch_based_model: false
  method: "model_instance"
  remove_punctuation: true
  lowercase: false
  keep_speakertags: false
  clean_embedding_tokens: true
  output_options:
    exclude_special_tokens: true
    remove_'_'_character: true
    remove_speaker_labels: true
    remove_punctuation_and_symbols: true
    remove_brackets_and_content: true

normalization_options:
  method: "lemmatization" #Options: lemmatization or stemming
