# Configuration file: variable parameters
# =======================================
input_file: "text" #or 'audio'

#PATH_TO_PROJECT_FOLDER: "/home/yvespauli/PycharmProjects/KetamineStudy/KetamineStudy_ProjectFolder/" # Set default to home directory, e.g., '/home/usr/...'
PATH_TO_PROJECT_FOLDER: "/home/yvespauli/PycharmProjects/DiscourseTest/"
language: "german" # Possibly add options for German and English
number_of_subjects: null # Specify number of subjects; if 'null', number of subjects is automatically detected
multiple_sessions: false # Set to True if multiple sessions per subject

recompute_everything: true #If set to 'false' pelican will try to reuse previously computed results stored on your drive

has_multiple_sections: false #evaluated independently
section_identification: null #e.g. "Section:", 'null' if file does not have multiple sections, use pattern that is unlikely to appear in rest of transcript
number_of_sections: null #if 'null' number of sections automatically detected, however, specifying number recommended if known.

discourse: true
number_of_speakers: 2
subject_speakertag: "B"

task_name: "interview" # Give name of task used for creation of the input file (e.g., ['fluency', 'interview'])
corpus_names:
  - "schizophrenia"

metric_to_extract: "embeddings"
extract_logits: null
extract_embeddings: true

tokenization: "wordLevel" # Options: 'characterLevel', 'subWordLevel'

# Options for extract_logits
chunk_size: null
overlap_size: null

# Options for extract_embeddings
window_sizes: [2]
metric_function: cosine_similarity
aggregation_functions: mean_of_means

cleaning_options:
  general_cleaning: true # General cleaning options used for most text preprocessing, default: True.
  remove_brackets_and_bracketcontent: true
  remove_timestamps: true
  timestamp_pattern_example: "#00:00:23-00#"

general_cleaning_options:
  strip_whitespace: true
  merge_multiple_whitespaces: true
  remove_whitespace_before_punctuation: true
  merge_newline_characters: true
  remove_backslashes: true

tokenization_options_logits:
  method: "model_instance" # Options: model_instance, regex, nltk, etc.
  model_name: "DiscoResearch/Llama3-German-8B-32k" # Replace with your model instance name
  remove_punctuation: true
  lowercase: true

tokenization_options_embeddings:
  method: "whitespace"
  remove_punctuation: true
  lowercase: true

normalization_options:
  method: "lemmatization" #Options: lemmatization or stemming
